### ISSUE TITLE
Style references should be a variable scope, not entity

### ISSUE THREAD

**Issue by FichteFoll** [jfcherng-sublime/ST-ASS#1]
(and definitely not `entity.name.function`)

Also, please use lower-cased names for your scopes, especially `entity.name.section`, which is a commonly used scope name.

**Comment by jfcherng** [comment]
Closed by https://github.com/jfcherng/Sublime-ASS/pull/4

**Comment by FichteFoll** [comment]
Oh wow, it's been almost 2 years. I nearly forgot I already complained about this.
