### ISSUE TITLE
How can I use it in My iOS Project？

### ISSUE THREAD

**Issue by syg1128** [jfcherng-sublime/ST-ASS#3]
How can I use it in My iOS Project？

**Comment by jfcherng** [comment]
What do you mean to use this in a iOS project? This is only for syntax highlighting.

**Comment by syg1128** [comment]
哥们，是中国的吗？ 我想在iOS工程中，实现提取ass、ssa字幕文件中文本，请问我该怎么实现？

**Comment by jfcherng** [comment]
這與此專案無關。
